// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQKgfoTtht73boIu-YzteVeo7C6DlPZe0',
    appId: '1:849767020443:web:d98365bbf580f380c5d33e',
    messagingSenderId: '849767020443',
    projectId: 'portfolio-flutter-75e51',
    authDomain: 'portfolio-flutter-75e51.firebaseapp.com',
    storageBucket: 'portfolio-flutter-75e51.appspot.com',
    measurementId: 'G-C2QPN6QECQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_wlgN63HL1txOQV7sgaIpkWGNgzGfMk',
    appId: '1:849767020443:android:52e3dddaee904de8c5d33e',
    messagingSenderId: '849767020443',
    projectId: 'portfolio-flutter-75e51',
    storageBucket: 'portfolio-flutter-75e51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG6NnSKABE2hcoIxwmA-vfOEbLSG3pxQ0',
    appId: '1:849767020443:ios:5f2ec5a81fcae55ac5d33e',
    messagingSenderId: '849767020443',
    projectId: 'portfolio-flutter-75e51',
    storageBucket: 'portfolio-flutter-75e51.appspot.com',
    iosBundleId: 'com.example.dhiravrana',
  );
}
