name: Dart

on:
  push:
    branches: [ "master" ] # Trigger the workflow on push events to the "master" branch
  pull_request:
    branches: [ "master" ] # Trigger the workflow on pull requests to the "master" branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build web
        run: flutter build web

      # Deployment steps
      - name: Deploy to ShiftAlpha.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: main # Deploy to the "main" branch of ShiftAlpha.github.io
          cname: dhiravrana.com # Optional: Add your custom domain if applicable
